### ISSUE TITLE
ERROR: Error forwarding the new session....

### ISSUE THREAD

**Issue by MichalDulemba** [hulilabs/webdriverio#3]
When i downloaded complete repository with example test (after running run) - i got: 

ERROR: Error forwarding the new session Empty pool of VM for setup Capabilities [{rotatable=true, locationContextEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@81ee3f7, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, requestOrigins={name=webdriverio, version=4.6.2, url=http://webdriver.io}}]

**Comment by stevevega** [comment]
@MichalDulemba I updated the example `docker-compose.yml` file and added a [Troubleshooting](https://github.com/hulilabs/webdriverio#troubleshooting) section. Take a look and let me know if you need something else.

Thanks.

**Comment by MichalDulemba** [comment]
Thanks a lot. Works!

**Comment by darrylb-github** [comment]
Any tips if I still get same error after following troubleshooting and making sure there is enough of a pause in between?

**Comment by tbradley-sans** [comment]
Like @darrylb-github, I'm having this same issue. Neither of the two workarounds solved my problem. One workaround doesn't work, because there is no bash shell in the container (see #11). And the other still gives the "Error forwarding the new session" error.

```$ docker-compose run --rm webdriverio wdio
Starting webdriverio_hub_1 ... done
Starting webdriverio_chrome_1  ... done
Starting webdriverio_firefox_1 ... done

[19:27:50]  COMMAND	POST 	 "/wd/hub/session"
[19:27:50]  DATA		{"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"browserName":"chrome","loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"4.14.1","name":"webdriverio"}}}
[19:27:50]  COMMAND	POST 	 "/wd/hub/session"
[19:27:50]  DATA		{"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"browserName":"firefox","loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"4.14.1","name":"webdriverio"}}}
ERROR: Error forwarding the new session Empty pool of VM for setup Capabilities {browserName: chrome, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.14.1}, rotatable: true}
chrome
    at new RuntimeError (/install/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
    at Request._callback (/install/node_modules/webdriverio/build/lib/utils/RequestHandler.js:318:39)
    at Request.self.callback (/install/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/install/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/install/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
ERROR: Error forwarding the new session Empty pool of VM for setup Capabilities {browserName: firefox, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.14.1}, rotatable: true}
firefox
    at new RuntimeError (/install/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
    at Request._callback (/install/node_modules/webdriverio/build/lib/utils/RequestHandler.js:318:39)
    at Request.self.callback (/install/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/install/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/install/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
```

**Comment by tbradley-sans** [comment]
@darrylb-github I think I found the problem. The docker-compose.yml file in Git is missing a necessary environment variable for each of the two browser containers. I debugged the Selenium scripts to find where they were failing, which led me to this. So if your problem was in running the example, that's why. I'll write up an issue for it and submit a PR.
